### ISSUE TITLE
Sprint 1: Home page, About page & Authentication

### ISSUE THREAD

**Issue by Koigor97** [Koigor97/pennywise#2]
**Tmeline:** August 12th - August 18th

### Goals:

- Set up project repo (images, svgs, icons, and other assets) and environment
- Develop the Home page to provide an overview of the application
- Develop the About page with detailed information about the project and the author
- Implement animation using framer motion
- Build the log-in and sign-up page
- Implement the user authentication system
- Integrate OAuth providers (GitHub, Google, LinkedIn)

### Tasks:

- [ ] Set up GitHub repository and GitHub Projects for task management
- [ ] Initialise the project with ReactJS, TypeScript, Shadcn UI, Tailwind CSS, etc.
- [ ] Implement authentication with Supabase
- [ ] Design and implement the Home page with key sections: Hero, Features, Testimonials, How It Works, and Call to Action
- [ ] Design and implement the About page with sections like Mission Statement, Vision, Goals, and About the Author
- [ ] Complete the home, about, login and sign-in pages
- [ ] Integrate OAuth providers for sign-in and sign-up
- [ ] Basic responsive design for the homepage, about, and authentication pages

### Deliverables: 

- [ ] Fully designed and responsive Home page
- [ ] Completed and responsive About page
- [ ] Functional user authentication system with OAuth
- [ ] Basic project structure
